# This cookbook should not be tested with the Docker driver
# Stick to libvirt and VirtualBox
---
driver:
  name: vagrant
  provider: libvirt
  # libvirt and the Fedora image are picky about which bridge nic you use
  # tinker with the dev value if you get explosions
  network:
    - ["public_network", { dev: "virbr0", mode: "bridge", type: "direct", mac: "52:54:00:12:34:56" }]

driver_config:
  customize:
    cpus: 4
    memory: 4096
    disk_bus: sata

provisioner:
  name: chef_zero
  data_bags_path: 'fixtures/data_bags'
  always_update_cookbooks: true

platforms:
  - name: fedora27_workstation
    driver_config:
      box: 'generic/fedora27'
    attributes:
      ax_workstation:
        sudo_groups:
          - sysadmin

suites:
  - name: default
    run_list:
      - recipe[ax_fedora_workstation::default]
