# This cookbook should not be tested with the Docker driver
# Stick to kvm and VirtualBox
---
driver:
  name: vagrant
  gui: true
  customize:
    cpus: 4
    memory: 4096

provisioner:
  name: chef_zero
  data_bags_path: 'fixtures/data_bags'
  always_update_cookbooks: true

platforms:
  - name: fedora27_workstation
    driver:
      box: 'generic/fedora27'
    attributes:
      ax_workstation:
        sudo_groups:
          - sysadmin

suites:
  - name: default
    run_list:
      - recipe[ax_fedora_workstation::default]
